version: 2
jobs:
  test:
    - checkout
    - run:
        name: Setup venv
        command: |
          echo 'export TAG=0.1.${CIRCLE_BUILD_NUM}' >> $BASH_ENV
          echo 'export IMAGE_NAME=blackjack-api' >> $BASH_ENV 
          virtualenv blackjack-api
          . blackjack-api/bin/activate
          pip install --no-cache-dir -r requirements.txt
    - run:
        name: Run Tests
        command: |
          . blackjack-api/bin/activate
          pytest
  build:
    docker:
      - image: docker:20.10.8-git
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-{{ .Branch }}
          paths:
            - /caches/app.tar
      - run:
          name: Load Docker image cache
          command: |
            set +o pipefail
            docker load -i /caches/app.tar | true
      - run:
          name: Build docker image
          command: docker build --cache-from=app -t app .
      - run:
          name: Save image cache
          command: |
            mkdir -p /caches
            docker save -o /caches/app.tar app
      - save_cache:
          key: v1-{{ .Branch }}-{{ epoch }}
          paths:
            - /caches/app.tar
workflows:
  test-and-deploy:
    jobs: test
