version: 2.1
orbs:
  python: circleci/python@1.4.0
jobs:
  test-app:
    executor: python/default
    steps:
      - checkout
      - python/test:
        args: '--dev'
        pkg-manager: pipenv
        test-tool: pytest
  build:
    docker:
      - image: docker:20.10.8-git
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-{{ .Branch }}
          paths:
            - /caches/app.tar
      - run:
          name: Load Docker image cache
          command: |
            set +o pipefail
            docker load -i /caches/app.tar | true
      - run:
          name: Build docker image
          command: docker build --cache-from=app -t app .
      - run:
          name: Save image cache
          command: |
            mkdir -p /caches
            docker save -o /caches/app.tar app
      - save_cache:
          key: v1-{{ .Branch }}-{{ epoch }}
          paths:
            - /caches/app.tar
